---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token-secret
  namespace: inference
spec:
  encryptedData:
    HF_TOKEN: AgCNUe9JGIlS293zCxpflVHLUArMaJxBe9aISwZ1ZCjXhWioZZqEDyUpRoOglKYAKtiYLd4tg7zekiRck4sMO9E1o9rJqopMPZJUB3FGZmU2RDRCbN6ASs5dQ3QYEzVRaoZ7703W6MVfotSXKxxM2F43hGJ2nsYydaqVOY8UDzqHDvVQEgati4+oOF4xRu/s+GiUfS9QKH8bC0t0k7r670M/P0k5M8QYMlg4Y3CYn8pcBO0ueGLWbYLxMh6uJCQ1EXLuPOBBDPc94Dz04aKJbejebawt3T3jW8xzXuol0l3yC1GXWOtqxvyeAH1hLxWdcMqHc/rDKP3z+Fbj5tNTFCndwnciRdY7YtyYgIgKtcYDJf5kPtLuvWF+NLtwQQKX0dpSO8DGO3y9Tnv4uSMaPmZhls7Dasatm50+xk5Et9BjLvQKB4VUo55TzpazQ341FBIKl/EUV9vm0zVBB4tiwqfCT8mMzuwrWO1WJOka95NNpEcUYK8UKsgxDQVVe29QFXvUBB/qeD16PvI9dXhkAKmi/062uuXK3Sab0xFI/HWjpBDoaDpMke/W0zzknGjDJd6C7f0CzjCWSCPMTxcQhCwn5YEjLLwN+hxhKYFbZAhTZA09tI779scrUNaHt6CJ4UN+xONcMYRtg+ds4xIfEvY66FfuMbq9PicmCuYWCYGUF8FsCJaYpp3z5MlCqjUkwBnDfCXKjTENmOofSrA6ZqwvZ0XWQvVfy10+Y5H6GS7TbIWGM3E4
  template:
    metadata:
      name: hf-token-secret
      namespace: inference
