kube-plex:
  kubePlex:
    enabled: true

  # Override this with the plex claim token from plex.tv/claim
  claimToken: "claim-jbvoJ9URV6R_k2WMPHkF"

  # Set the timezone of the plex server
  timezone: Europe/Lisbon

  ingress:
    enabled: false

  persistence:
    transcode:
      claimName: pvc-plex-transcode
    data:
      claimName: pvc-plex-data
    config:
      claimName: pvc-plex-config
