kube-plex:
  kubePlex:
    enabled: true

  # Override this with the plex claim token from plex.tv/claim
  claimToken: "claim-Hn-V_EBHkYrtzWn2rmvQ"

  # Set the timezone of the plex server
  timezone: Europe/Lisbon

  ingress:
    enabled: false

  persistence:
    transcode:
      enabled: true
      claimName: pvc-plex-transcode
    data:
      claimName: pvc-plex-data
    config:
      claimName: pvc-plex-config

  resources:
    limits:
     cpu: 1
    requests:
     cpu: 100m

  nodeSelector:
    kubernetes.io/arch: amd64
    intel.feature.node.kubernetes.io/gpu: true
