kube-plex:
  kubePlex:
    enabled: true

  # Override this with the plex claim token from plex.tv/claim
  claimToken: "claim-GyyZt8JbYzY4fVcZv1Yg"

  # Set the timezone of the plex server
  timezone: Europe/Lisbon

  ingress:
    enabled: false

  persistence:
    transcode:
      claimName: pvc-plex-transcode
    data:
      claimName: pvc-plex-data
    config:
      claimName: pvc-plex-config

  plex:
    # The UID and GID that the Plex Media Server should run as.
    uid: 1000
    gid: 1000
