apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mqtt-external
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto:2
        ports:
        - containerPort: 1883
        volumeMounts:
         - name: certs-mqtt
           mountPath: "/mosquitto/certs"
           readOnly: true
         - name: passwd-mqtt
           mountPath: "/mosquitto/security"
           readOnly: true
         - name: conf-mqtt
           mountPath: "/mosquitto/config"
           readOnly: true
      volumes:
      - name: certs-mqtt
        secret:
          secretName: certs-mqtt
      - name: passwd-mqtt
        secret:
          secretName: passwd-mqtt
      - name: conf-mqtt
        configMap:
          name: mqtt
