{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "daikin-credentials",
    "namespace": "climate-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "daikin-credentials",
        "namespace": "climate-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "client_secret": "AgCm7gyr1EsaBH6I/9AElSAfWF87TisOnVWzd4p4Fl6xJFzAul4XM2vLmuluO/9LGF+gEtvWz9Ah4AfxLJhOGnxz7kaTIAga3YRLf5SbM/eLlMlsqCbGQXQwIRihXinN5l90g3YV/vJZ2JhAq+R4/5Sjsn8R+PWsEImv4cf+XroCXQVLw0PHyElLP/D32Mlk65dHGD8usjOXZEHhoceE3EFmU5yYSMTLjBhDqssYnmBlY5KbNnUBdlNEqXZlZI+gNIgjVwf4jPJC5dKkGB6Y9pXtHeC7yG7Qeo87oXPRAYvNUTEDqB/bT0+uaFUZT2oRdRp05AGzzi7EWn+tbpvoKhX9LtsurK2C0mAqQ4DsJVXbQ8WmSItiHiY5RL8UFVeMDm6Dqo5AqH5dMsgb4sser0YR8NrCZIfZ208C+nShrtDG9wEDVrMjnk2gcoDi6Il0uBlt99xakwNUXzr2yiKrN7BCmBpXVaVMzQbXKBveRI5v00dPs7XxFauO5brKeSXQnJphczRICTDJN88iw2lqNi3052LdrT40KQP6woki6H6rzx9WdN/KRftGLSlEWV5iegjWRJkyZzssmcJg+zeOFOs4fwneN9rSJww+qm0jKvUsmZvD1I0yi5AOAbpU9UZnEwsElIVr3bJg1mdLwhUnEdQO/qZWbZiekTa4Y4CTSvfJ89JrVAg/v+bYhg/stv2xy8Psu3V3AdrOQEofD79ePD9gdBIYs11zsql5WZf+MUc0MAZAP3dEYiw73X0ZdsNjwBc04gJIrjH9TGC9QpB4MJ8MLc8mRA9DaWw8twdrokdpKogldG0tEg=="
    }
  }
}
