apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: climate-system
  name: daikin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
  - secretName: certs-daikin-ingress
    hosts:
    - daikin.88288338.xyz
  rules:
  - host: daikin.88288338.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: daikin
            port:
              number: 8080

