apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-climate-controller
  namespace: climate-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10M

