---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  clusterIP: None
  ports:
  - name: influxdb
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
