{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "daikin-credentials",
    "namespace": "daikin-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "daikin-credentials",
        "namespace": "daikin-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "client_secret": "AgAM6kwygPMq51YkWvMCHDAz8w3eUKV1FBwY8dQfhtgbhZDGUo0S5YAAK4b72p/d0AJkk3eEmxZFCUZ5HTX2OdzZOiP5+SSPg1LFyKxDehVvVfBKDmQtXCxUtmcjEM7rwa6tk+L4DEjQZdsQsmzTm6y0A3uUT5B3fLjsJo7VDBwsZjOkhbVGF45/pCV5GXS5MjDzRIHxtQe5S/R2LmZnZZq3B8aOSdRze3WuscdpR1mqUZ86dZSy5DVpGqwaHS49uteoEW5YQqrOzIYvSemheMxRArdNHMhJ2bWbPHp8Cpqx3RKwQhfhCm1LmVpbGCCHW40GVG0PbQ+scDsv0tCL1i80aXZ11GyV4yi2A6Q4CbfmjLJ9Fxhj2k0vmtMJNkdVU02x1E3ejEIh4RHxmpZkv7Cl5Wi+d+RIXmEIg1cxAGcrys7XVnnVcBf1LFka/zaS1flgj8gwITJu7Yo6rS6yuQx9DCjYoPgUuKXnPmny1PjWYRylDAP7jV1q6BXqINMuDSQnClNPR1s7GNFoneBe6/WJoeWuii0LRAiN1XAr60n3XUn8lvfCOVY4fv7zwt8Qqsga9nbQJvWOUdpGGV9BIvzy0Z15lREbDuntMT904T/r0U18RtwZ1n4S44KPLxK114deaihy3ya1S4rJRQ7BEHjCo+4JVpx8RerK9AtlX6NoEvkWXkSB1G9VdXn1oqgjfExUrMDNNE0BS971sFUVCbijjEz5k/ODVcjwlV4ay+Yh9KpXeDTc3HKRSC6JTMHcjq717Y2i/zRniRxQHoKd5MgbhzTaswrwn+ELIrWL9HKR+qAiR379uw=="
    }
  }
}
