apiVersion: apps/v1
kind: Deployment
metadata:
  name: daikin-controller
  labels:
    app: daikin-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daikin-controller
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: metrics
        prometheus.io/scrape: "true"
      labels:
        app: daikin-controller
    spec:
      containers:
      - image: registry.88288338.xyz:5000/daikin-controller:latest
        name: controller
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
        env:
        - name: DAIKIN_CLIENT_ID
          value: {{ .Values.daikin.client_id }}
        - name: DAIKIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: daikin-credentials
              key: client_secret
        - name: DAIKIN_GATEWAY_DEVICE_ID
          value: {{ .Values.daikin.gateway_device_id }}
        - name: DATA_DIR
          value: /data
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-daikin-controller



