apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-daikin-controller
  namespace: daikin-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10M

