apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: default
  namespace: nodered
spec:
  virtualhost:
    fqdn: nodered.88288338.xyz
    tls:
      secretName: certs-ingress
  routes:
    - services:
      - name: nodered
        port: 80
    - conditions:
      - prefix: /comms
      enableWebsockets: true # Setting this to true enables websocket for all paths that match /websocket
      services:
      - name: nodered
        port: 80
