apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nodered
  name: nodered
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
  - secretName: certs-ingress
    hosts:
    - nodered.88288338.xyz
  rules:
  - host: nodered.88288338.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nodered
            port:
              number: 80
