---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mailserver-accounts
  namespace: mailserver
spec:
  encryptedData:
    postfix-accounts.cf: AgAfjfsUez6AVyyN7bbwn7/biyuNEhz04yHs8F2+rjDIq0KM25pV4Q/yg1LJQPcwNOg5QbHBOVUEMlaKX+290K5inAPzfZQa1WxFZb7TVuETvaZlOdSMXSgGIi7LQ1QhsjMtrcACYGHmQ+obhEAXBDx+4Xlvbx4eDumltg6xbtEWjIXK2NBPsNBypmzTum8O+csO6oWsym/DmvOpSy5dsVm63LMeU+ouJZX7P1J3Hnl1UFgrlwkSAf9+QkcVR8kXoxD8jhWHzT3pgTJzC+1DQBZft7t1eQl+q8ETcSFn7+90T7vsIZXvXKCZnhqYxz4twm3O/V4y+qifKdNUjFOvOJiCQ4F5cXW5CiS+i2z1U5WHFPK3oYkUOxVCxNycmBmUeit5R+HaYrBSMTNwMfuK690Zx+HUAV0KRsFwhg9AfJGi+orHQIE7gNA10KOe522AhET+8+lXjeW80sWZeEU84le8+GZz5RzWJ0t9uEHTqlWUpR2aUjqiljkO87VjH4mDiE0i5j2zWY7sXZ0dwaAvm50uFDxZ/R05AWTCN+qUb3DNjMb4vqZ1VIbezDbu/ZdrdiYUU4ZDqD9oVRBIrf/ytbfk8oQQDrgUPI48unj1mdlyhvoT/OUzDtYrJRgBY9sJ6UbNN5fCZ3mtz8E8GPFqwIT5o7FDOlIv5fSSMIa33Dk74Z2BL4uSRW4anDxaNYQZgQeP0UOcTFSEbzpH805AwbisFyogTE6e7snp7KszMRDBgHASTR8nInDjWrGVF+jEMHBoKdeS/NjjO5HiWCwf6E5fQ1VQi3JIppEGMGU/miNFK1vPp/aipIr3a24p8JbQE+UOwxbVZBUfMBXZWawnm+m/F5SPle2Mjti0Rw9HZjpMpgTeBJIue1FIFp3T
  template:
    metadata:
      name: mailserver-accounts
      namespace: mailserver
