apiVersion: v1
kind: Service
metadata:
  namespace: plex
  labels:
    app: kube-plex
  name: kube-plex-external
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32401
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app: kube-plex

