apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certs-eot-ingress
spec:
  dnsNames:
  - api.eot.pt
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: certs-eot-ingress
  usages:
  - digital signature
  - key encipherment
