apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: plex
  name: qbittorrent
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
  - secretName: certs-qbittorrent-ingress
    hosts:
    - torrent.88288338.xyz
  rules:
  - host: torrent.88288338.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: qbittorrent
            port:
              number: 8080
