apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent-config
  namespace: plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: longhorn
