apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-data
  namespace: plex
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

